version: "3"
services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - <path/to/your/config>:/etc/nginx
      - <path/to/your/certs>:/etc/ssl/private
  backend:
    image: datascientist69/reliefo:relief_web
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  mongo:
    image: mongo
#    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongodb/db:/data/db
    command: --quiet --auth
  react:
    image: react_app:v1
    build:
      context: ./relief_customer/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./relief_customer/:/code
