version: "3"
services:
  web:
    image: datascientist69/reliefo:relief_webv1
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  mongo:
    image: mongo
#    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db