version: "3"
services:
  backend:
    image: datascientist69/reliefo:relief_web
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      logging:
      driver: awslogs
      options:
       awslogs-region: ap-south-1
       awslogs-group: agent_007
       awslogs-create-group: 'true'
       awslogs-stream: stdout
  mongo:
    image: mongo
#    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongodb/db:/data/db
    command: --quiet --auth
  react:
    image: 020452232211.dkr.ecr.ap-south-1.amazonaws.com/liqr_react:latest
    #    build:
    #  context: ./relief_customer/
    #  dockerfile: ./Dockerfile
    ports:
      - "81:81"
    volumes:
      - ./relief_customer/:/code
