
variables = {'--theme-font': 'Poppins',
             '--first-background-color': '#ffffff',
             '--second-background-color': '#ffffff',
             '--first-menu-background-color': '#f0f0f0',
             '--second-menu-background-color': '#f0f0f0',
             '--first-light-color': '#ffc967',
             '--second-light-color': '#ffa813',
             '--first-pattern-light-color': '#ffb023',
             '--second-pattern-light-color': '#ffb023',
             '--food-card-color': '#ffffff',
             '--welcome-card-color': '#ffffff',
             '--welcome-card-text-color': '#000000',
             '--food-menu-button-color': '#ffb023',
             '--add-button-color': '#ffb023',
             '--top-bar-color': '#ffb023',
             '--search-background-color': '#ffc45c',
             '--burger-menu-background-color': '#c0841d',
             '--first-footer-color': '#ffb023',
             '--second-footer-color': '#ffb023',
             '--categories-button-color': '#ffb023',
             '--categories-list-item-color': '#ffffff',
             '--table-cart-color': '#ffb023'}
variable_names = {'--theme-font': 'Theme Font, ignore this',
                  '--first-background-color': 'Home Screen Background Color',
                  '--second-background-color': 'Home Screen Background Color2',
                  '--first-menu-background-color': 'Menu and Other Screens Background Color',
                  '--second-menu-background-color': 'Menu and Other Screens Background Color2',
                  '--first-light-color': 'Theme color which is blended for Need Help Choosing',
                  '--second-light-color': 'Theme color which is blended for Need Help Choosing 2',
                  '--first-pattern-light-color': 'Color for all other objects',
                  '--second-pattern-light-color': 'COlor for all other objects 2',
                  '--food-card-color': 'Food Item Card Color',
                  '--welcome-card-color': 'Welcome to Restaurant Card Color',
                  '--welcome-card-text-color': 'Welcome to Restaurant Text Color',
                  '--food-menu-button-color': 'Full Menu Button color',
                  '--add-button-color': 'Add button in food items color',
                  '--top-bar-color': 'Top bar color',
                  '--search-background-color': 'Search bar color',
                  '--burger-menu-background-color': 'Side menu background color',
                  '--first-footer-color': 'Footer color 1',
                  '--second-footer-color': 'Footer color 1',
                  '--categories-button-color': 'Floating categories button in menu screen color',
                  '--categories-list-item-color': 'Floating categories item color',
                  '--table-cart-color': 'Table cart  orders background color'}
